/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://xmy6qqt73nhhlipmgwisned4ai.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gjukvztgtbdbvnaj44enmi5eoy",
    "aws_cognito_identity_pool_id": "us-east-2:85140f35-83fa-4985-a580-0b8727e399fc",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_yGE9c0U2u",
    "aws_user_pools_web_client_id": "v11aq94ge9rp9g15j5hfb0h3",
    "oauth": {}
};


export default awsmobile;
